print("Hello World")
print("Hello there")
print("I tried this alot of times but i skipped alot")
print("But not i'm really don't want to skip ")
print("My decition is 'Final', i won't change my mind")
